spring:
  application:
    name: crms_backend
  datasource:
    url: jdbc:mysql://localhost:3306/cams
    username: admin
    password: VTCATFYPP@$$w0rd
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 8787
  address: 0.0.0.0
