spring:
  config:
    import: optional:classpath:application-secret.yml
  application:
    name: crms_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true       # 465 端口必須啟用 SSL
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


security:
  jwt:
    expire_time: 3600
server:
  port: 8787
  address: 0.0.0.0
