spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camsDB
    username: DBusername
    password: DBpassword
  mail:
    username: googleAccount@gmail.com
    password: appPassword

file:
  upload-dir: C:\CAMS

security:
  jwt:
    secret: "youJwtSecretKeyInHS256"